"""Offline payload mapping for future real OpenEO create-job requests."""

from __future__ import annotations

from dataclasses import asdict, is_dataclass
from typing import Any


def _to_mapping(submit_request: Any) -> dict[str, Any]:
    if is_dataclass(submit_request):
        return asdict(submit_request)
    return dict(submit_request or {})


def build_create_job_payload(submit_request: Any) -> dict[str, Any]:
    payload = _to_mapping(submit_request)
    capabilities_source = payload.get("capabilities_source")
    process_graph_preview = dict(payload.get("process_graph_preview") or {})

    if capabilities_source == "mock":
        return {
            "success": False,
            "error": "mock_capabilities_cannot_build_real_submit_payload",
            "not_submitted": True,
            "warnings": ["mock capabilities cannot be used for real submit payload preparation"],
        }

    if not process_graph_preview:
        return {
            "success": False,
            "error": "missing_process_graph_preview",
            "not_submitted": True,
            "warnings": [],
        }

    warnings: list[str] = []
    if capabilities_source == "real_cached":
        warnings.append("cached capabilities are not live backend state")
    elif capabilities_source != "real":
        warnings.append("payload is not approved for live backend submit")

    request_id = payload.get("request_id")
    preview_id = payload.get("preview_id")
    backend_url = payload.get("backend_url")

    job_payload = {
        "title": f"Hermes OpenEO job draft {request_id}",
        "description": (
            "Approval-gated OpenEO create_job payload preview generated by Hermes. "
            "This payload has not been submitted."
        ),
        "process": {
            "process_graph": process_graph_preview,
        },
        "metadata": {
            "request_id": request_id,
            "preview_id": preview_id,
            "created_by": payload.get("created_by", "local_user"),
            "capabilities_source": capabilities_source,
            "backend_url": backend_url,
        },
    }
    return {
        "success": True,
        "payload": job_payload,
        "warnings": warnings,
        "not_submitted": True,
    }
